#!/usr/bin/env bash
# add a custom Nginx response header.

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:80 default_server;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/sites-available/default
sudo service nginx restart
