#!/usr/bin/env bash
# Ping an address

if [ "$#" -eq 0 ]; then
	echo -e "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

i=0
for arg in "$@"; do
	[[ $i -ge 1 ]] && echo -e
	ping -c 5 "$arg"
	i+=1
done
