#!/usr/bin/env bash
# disable a site, remove the symbolic link and enable site again
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /run/nginx.pid)"
