#!/usr/bin/env bash
# using while, if...elif
count=1
while [[ count -le 10 ]];
do
if [[ count -eq 4 ]];
then
echo "bad luck"
elif [[ count -eq 8 ]];
then
echo "good luck"
else
echo "Best School"
fi
(( count++ ))
done
