#!/usr/bin/env bash
# Gives info about school file
list=$(ls)
for list_item in $list
do
	if [[ $list_item == school ]];then
		file=$list_item
	fi
done
if [[ -e $file ]];then
echo "school file exists"
if [[ ! -s $file ]];then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [[ -f $file ]];then
	echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
