#!/usr/bin/env bash
# Run nginx as nginx user instead of root
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo chmod a+rwx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
